package org.whysexplorer.content

import org.whysexplorer.models.{DifficultyLevel, Question}

object AnimalsQuestions {

  val all: List[Question] = List(

    Question("animals-006", "animals",
      "Why do dogs wag their tails?",
      "A dog's tail is basically a mood display screen. Fast wagging with the tail held high means 'I'm so excited!' A slow wag with the tail tucked low means 'I'm a bit nervous.' Dogs evolved in packs where they couldn't always bark without getting into trouble, so body language became their main way of talking. The cool part? Dogs only wag their tails at other animals and people — never when they're alone.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/dog-wag.avif"), Some("/assets/animations/animals/dog-wag.json"),
      Some("/assets/audio/en/animals-006.mp3"),
      List("Dogs don't wag their tails when they're on their own — it's 100% a communication tool, never just a habit!",
           "Puppies don't start wagging until they're about 6–7 weeks old — before that they haven't learned the language yet."),
      List("dogs","behavior","body language"), 8, 12),

    Question("animals-007", "animals",
      "Why do snakes flick their tongue?",
      "A snake's tongue is a smell collector, not a tasting tool. When the tongue flicks out, it picks up tiny scent particles floating in the air. Then it plugs into two pits inside the mouth called Jacobson's organs, which analyse the scent. The tongue is forked so one tip can sample the left side and the other the right — giving the snake 3D smell direction, like a live GPS tracking system for prey.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/snake-tongue.avif"), Some("/assets/animations/animals/snake-flick.json"),
      Some("/assets/audio/en/animals-007.mp3"),
      List("Because the tongue is forked, snakes can tell which direction a smell is coming from — left fork stronger means the prey is to the left!",
           "Pit vipers have an extra superpower: special heat sensors near their nose can detect a mouse's body warmth in total darkness."),
      List("snakes","senses","smell"), 8, 12),

    Question("animals-008", "animals",
      "Why do flamingos stand on one leg?",
      "Standing on one leg lets flamingos keep warm without burning extra energy. When they tuck one leg up close to their body, less skin is exposed to cold water or cold air — losing heat only through one leg instead of two. Their leg joints have a special locking system so they don't need any muscle effort to stay balanced. It's like locking a bicycle stand — it just clicks into place.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/flamingo.avif"), None,
      Some("/assets/audio/en/animals-008.mp3"),
      List("Flamingos are born completely grey and white. Their pink colour builds up slowly from pigments in the shrimp and algae they eat!",
           "A group of flamingos is called a flamboyance — one of the coolest group names in the animal world."),
      List("flamingos","birds","behavior"), 8, 12),

    Question("animals-009", "animals",
      "Why do bees make honey?",
      "Bees make honey because they need food to survive winter. Flowers stop blooming in the cold months, so bees spend summer collecting nectar and turning it into long-lasting energy bars — honey. They suck up nectar, mix it with special chemicals from their stomachs, store it in wax cells, then fan it with their wings to dry it out until it's thick and sticky. One jar of honey represents the entire life's work of about 1,000 bees.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/bee-honey.avif"), Some("/assets/animations/animals/bee-dance.json"),
      Some("/assets/audio/en/animals-009.mp3"),
      List("A single bee makes only about one-twelfth of a teaspoon of honey in its whole life. It takes a lot of bees to fill a jar!",
           "Honey found in 3,000-year-old Egyptian tombs was still perfectly edible — honey basically never goes bad."),
      List("bees","insects","honey","food"), 8, 12),

    Question("animals-010", "animals",
      "Why do octopuses have three hearts?",
      "An octopus body is so complex it needs a whole extra set of pumps. Two smaller hearts push blood to the gills to pick up oxygen, and one big central heart pumps that oxygen-filled blood to the rest of the body. What makes octopuses really weird is that their blood is blue — it uses copper instead of iron to carry oxygen, which works better in cold, deep ocean water.",
      DifficultyLevel.Advanced,
      Some("/assets/images/animals/octopus.avif"), Some("/assets/animations/animals/octopus-swim.json"),
      Some("/assets/audio/en/animals-010.mp3"),
      List("When an octopus swims, its main heart actually stops beating — which is why octopuses prefer crawling along the sea floor instead!",
           "An octopus has nine brains: one central brain plus a mini-brain in each of its eight arms. Each arm can act on its own."),
      List("octopus","marine","anatomy"), 8, 12),

    Question("animals-011", "animals",
      "Why do fish swim in schools?",
      "Imagine trying to catch one specific ball from a pile of hundreds of identical bouncing balls. That's what it's like for a shark attacking a school of fish. The flashing, swirling group confuses the predator because it can't single out one target. Swimming in a group also saves energy — each fish gets a small push from the water movement of the fish ahead of it, like cyclists drafting in a race.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/fish-school.avif"), Some("/assets/animations/animals/fish-school.json"),
      Some("/assets/audio/en/animals-011.mp3"),
      List("Fish in a school can change direction in less than a millisecond — faster than any single brain could react. They sense each other through a special vibration system called the lateral line.",
           "Some schools of fish contain millions of individuals and stretch for several kilometres."),
      List("fish","marine","behavior","groups"), 8, 12),

    Question("animals-012", "animals",
      "Why do polar bears have white fur?",
      "Polar bear fur isn't actually white — it's see-through! Each hollow hair is colourless and transparent. When light hits all those clear hairs piled together, it scatters and appears white — the same reason snow looks white. This perfect camouflage lets them creep up on seals without being spotted. Underneath all that fur, their skin is jet black, which soaks up every bit of the Sun's warmth.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/polar-bear.avif"), None,
      Some("/assets/audio/en/animals-012.mp3"),
      List("Polar bears can overheat while running, even in the Arctic! Their fur is too good at trapping heat.",
           "A polar bear can smell a seal hidden under 1 metre of ice from 1 kilometre away — one of the best noses in the animal kingdom."),
      List("polar bears","camouflage","adaptation","arctic"), 8, 12),

    Question("animals-013", "animals",
      "Why do spiders spin webs?",
      "Spiders build webs as an invisible food trap. Flying insects can't see the sticky silk threads, so they fly straight into them and get stuck. The spider can feel even tiny vibrations through the web — it instantly knows something is caught and exactly where. Some spiders also use their web as a home, a nursery for their eggs, and even as a musical instrument: they pluck the threads to 'listen' to what's been caught.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/spider-web.avif"), Some("/assets/animations/animals/spider-spin.json"),
      Some("/assets/audio/en/animals-013.mp3"),
      List("Spider silk is stronger than steel by weight. Scientists are trying to copy it to make better body armour and medical stitches!",
           "Many spiders eat their old web every morning to recycle the silk protein, then spin a fresh one. Nothing goes to waste."),
      List("spiders","web","predator"), 8, 12),

    Question("animals-014", "animals",
      "Why do whales breach (jump out of the water)?",
      "Scientists are honestly still working this one out! The best current ideas are: breaching knocks off barnacles and parasites clinging to the whale's skin, the massive splash sends sound signals to other whales far away (water carries sound much better than air), or — and this is a real scientific theory — they might simply do it for fun. Young whales breach far more than adults, which supports the 'playing' idea.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/whale-breach.avif"), Some("/assets/animations/animals/whale-breach.json"),
      Some("/assets/audio/en/animals-014.mp3"),
      List("A humpback whale weighs up to 36 tonnes — about the same as 5 double-decker buses — and it launches its entire body out of the water!",
           "Humpback whale songs can travel for thousands of kilometres through the ocean, and each population has its own regional 'dialect'."),
      List("whales","marine","behavior"), 8, 12),

    Question("animals-015", "animals",
      "Why do giraffes have long necks?",
      "Long necks help giraffes reach leaves at the top of acacia trees that no other animal can get to — like having a built-in ladder. But there's a second reason: male giraffes fight each other using their necks like giant clubs, a behaviour called necking. The giraffe with the longer, stronger neck usually wins, gets the females, and has more babies. Over millions of years, both reasons pushed neck length longer and longer.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/giraffe.avif"), None,
      Some("/assets/audio/en/animals-015.mp3"),
      List("A giraffe's neck can be 1.8 metres long — but it still only has 7 neck bones, the same number as a human!",
           "Giraffes sleep for only about 30 minutes a day, usually in short 5-minute naps. Their huge body takes too much energy to lie down safely for long."),
      List("giraffes","adaptation","evolution","africa"), 8, 12)
  )
}
