package org.whysexplorer.content

import org.whysexplorer.models.{DifficultyLevel, Question}

object AnimalsQuestions {

  val all: List[Question] = List(

    Question("animals-006", "animals",
      "Why do dogs wag their tails?",
      "A wagging tail is a dog's way of talking! A tail held high and wagging fast usually means excitement. A slow wag with a lowered tail can mean nervousness. Dogs evolved this because they live in packs where body language is their main language.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/dog-wag.avif"), Some("/assets/animations/animals/dog-wag.json"),
      Some("/assets/audio/en/animals-006.mp3"),
      List("Dogs don't wag their tails when they're alone — it's only for communicating with others!",
           "Puppies don't start wagging until they're about 6–7 weeks old."),
      List("dogs","behavior","body language"), 4, 12),

    Question("animals-007", "animals",
      "Why do snakes flick their tongue?",
      "A snake's tongue is a super-powered smell detector! When it flicks out, it collects tiny scent particles from the air and ground. Back inside the mouth, the tongue plugs into a special organ called the Jacobson's organ which identifies the smell — like a GPS for finding food.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/snake-tongue.avif"), Some("/assets/animations/animals/snake-flick.json"),
      Some("/assets/audio/en/animals-007.mp3"),
      List("Snakes have a forked tongue so they can smell in stereo — left and right at the same time!",
           "Some snakes can detect the body heat of prey with special pit organs near their nose."),
      List("snakes","senses","smell"), 5, 12),

    Question("animals-008", "animals",
      "Why do flamingos stand on one leg?",
      "Scientists believe flamingos stand on one leg to stay warm! Tucking one leg close to their body keeps heat from escaping through cold water. It's also remarkably easy for them — they can sleep this way because of a special locking mechanism in their joints.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/flamingo.avif"), None,
      Some("/assets/audio/en/animals-008.mp3"),
      List("Flamingos are born grey and white — their pink colour comes from pigments in the shrimp they eat!",
           "A group of flamingos is called a flamboyance."),
      List("flamingos","birds","behavior"), 4, 12),

    Question("animals-009", "animals",
      "Why do bees make honey?",
      "Bees make honey as their winter food store. They collect nectar from flowers, mix it with special enzymes in their stomachs, and deposit it in wax cells. Then they fan it with their wings to evaporate water — turning runny nectar into thick, energy-rich honey.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/bee-honey.avif"), Some("/assets/animations/animals/bee-dance.json"),
      Some("/assets/audio/en/animals-009.mp3"),
      List("A single bee makes only about one-twelfth of a teaspoon of honey in its entire life!",
           "Honey never goes bad — edible honey was found in 3000-year-old Egyptian tombs."),
      List("bees","insects","honey","food"), 4, 12),

    Question("animals-010", "animals",
      "Why do octopuses have three hearts?",
      "Two hearts pump blood to the gills to pick up oxygen, and one central heart pumps the oxygenated blood to the rest of the body. Octopuses also have blue blood — it contains copper instead of iron, which works better in cold, low-oxygen ocean water.",
      DifficultyLevel.Advanced,
      Some("/assets/images/animals/octopus.avif"), Some("/assets/animations/animals/octopus-swim.json"),
      Some("/assets/audio/en/animals-010.mp3"),
      List("When an octopus swims, the main heart actually stops beating — which is why they prefer crawling!",
           "Octopuses have nine brains: one central brain and one mini-brain in each of their eight arms."),
      List("octopus","marine","anatomy"), 7, 12),

    Question("animals-011", "animals",
      "Why do fish swim in schools?",
      "Swimming in a tight group (called a school) confuses predators. A shark sees hundreds of flashing fish instead of one easy target. It also makes each fish more efficient — like cyclists drafting in a race — because their neighbours' movement creates waves that push them forward.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/fish-school.avif"), Some("/assets/animations/animals/fish-school.json"),
      Some("/assets/audio/en/animals-011.mp3"),
      List("Fish in schools can synchronise their movements in milliseconds — faster than thought!",
           "Some schools contain millions of fish and can stretch for miles."),
      List("fish","marine","behavior","groups"), 5, 12),

    Question("animals-012", "animals",
      "Why do polar bears have white fur?",
      "Polar bear fur isn't actually white — it's colourless and transparent! Each hollow hair reflects and scatters light, making it look white against the snow. This perfect camouflage lets them sneak up on seals. Under the fur, their skin is actually black to absorb the sun's warmth.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/polar-bear.avif"), None,
      Some("/assets/audio/en/animals-012.mp3"),
      List("Polar bear fur is so good at trapping heat that they can overheat while running!",
           "A polar bear can smell a seal under 1 metre of ice from 1 kilometre away."),
      List("polar bears","camouflage","adaptation","arctic"), 6, 12),

    Question("animals-013", "animals",
      "Why do spiders spin webs?",
      "Spiders spin webs mainly to catch food — the sticky spiral threads trap flying insects. But webs also serve as homes, nurseries for eggs, and even as musical instruments: spiders pluck their web threads to 'hear' what's caught. Different spider species spin completely different web shapes.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/spider-web.avif"), Some("/assets/animations/animals/spider-spin.json"),
      Some("/assets/audio/en/animals-013.mp3"),
      List("Spider silk is stronger than steel by weight — scientists study it to make bulletproof materials!",
           "Some spiders recycle their webs by eating them to recover the protein."),
      List("spiders","insects","web","predator"), 4, 12),

    Question("animals-014", "animals",
      "Why do whales breach (jump out of the water)?",
      "Scientists aren't 100% sure, but the best guesses are: it removes parasites from their skin, it's a way of communicating with other whales (the splash travels far underwater), or it might just be for fun! Young whales breach far more often than adults.",
      DifficultyLevel.Medium,
      Some("/assets/images/animals/whale-breach.avif"), Some("/assets/animations/animals/whale-breach.json"),
      Some("/assets/audio/en/animals-014.mp3"),
      List("A humpback whale breach means its 36-tonne body leaves the water entirely!",
           "Whale song can travel thousands of kilometres through the ocean."),
      List("whales","marine","behavior"), 5, 12),

    Question("animals-015", "animals",
      "Why do giraffes have long necks?",
      "Giraffes' long necks help them reach leaves high in acacia trees that shorter animals can't get to. But they also evolved for competition — male giraffes use their necks to fight rivals in a behaviour called 'necking'. Longer necks win more fights and more mates.",
      DifficultyLevel.Simple,
      Some("/assets/images/animals/giraffe.avif"), None,
      Some("/assets/audio/en/animals-015.mp3"),
      List("A giraffe's neck is about 1.8 metres long but contains the same number of neck bones as a human (7)!",
           "Giraffes only sleep about 30 minutes a day, usually in short 5-minute naps."),
      List("giraffes","adaptation","evolution","africa"), 4, 12)
  )
}
