package org.whysexplorer.content

import org.whysexplorer.models.{DifficultyLevel, Question}

object HumanBodyQuestions {

  val all: List[Question] = List(

    Question("body-001", "human-body",
      "Why do we yawn?",
      "Scientists now think yawning is your brain's cooling system. When you're tired or bored, your brain temperature creeps up a little. Yawning opens your mouth wide and floods the area around your brain with cooler air, dropping the temperature back down — like cracking open a laptop lid to let it breathe. That's also why yawning is contagious: when you see someone yawn, your empathy brain circuits copy the behaviour, and your brain gets a cool-down too.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/yawn.avif"), Some("/assets/animations/body/yawn.json"),
      Some("/assets/audio/en/body-001.mp3"),
      List("Even reading the word 'yawn' can trigger a real yawn — try to get through this card without yawning!",
           "Babies in the womb start yawning at just 11 weeks old. Scientists think it helps develop the jaw muscles."),
      List("brain","behavior","yawning"), 8, 12),

    Question("body-002", "human-body",
      "Why do we get goosebumps?",
      "Goosebumps are a leftover feature from when humans were covered in thick body hair, millions of years ago. When your ancient hairy ancestors got cold or scared, tiny muscles pulled their hair upright, trapping warm air close to the skin and making them look bigger to scare off enemies — like a cat fluffing up. We still have those tiny muscles under our skin, but not enough hair for it to be useful. So we just get the bumps without the puffed-up fur.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/goosebumps.avif"), None,
      Some("/assets/audio/en/body-002.mp3"),
      List("The scientific word for goosebumps is 'cutis anserina' — Latin for 'goose skin'. Geese have the same reaction when their feathers stand up!",
           "A powerful piece of music can give you goosebumps too — scientists call that 'frisson'. It happens because your brain interprets the beauty as something exciting and triggers the same response."),
      List("skin","evolution","cold","fear"), 8, 12),

    Question("body-003", "human-body",
      "Why does our heart beat?",
      "Your heart is a pump made entirely of muscle, and it's working every second of your life without a single day off. Every beat squeezes blood out to every corner of your body — carrying oxygen and nutrients to your muscles and organs, and picking up waste to take away. The 'lub-dub' sound you hear through a stethoscope is the valves inside your heart snapping shut after each squeeze to make sure blood flows the right way and doesn't leak back.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/heart.avif"), Some("/assets/animations/body/heartbeat.json"),
      Some("/assets/audio/en/body-003.mp3"),
      List("Your heart beats about 100,000 times every day and around 2.5 billion times in your whole lifetime — without ever taking a break!",
           "A blue whale's heart is about the size of a small car and beats just 4–8 times per minute. A hummingbird's heart beats 1,200 times per minute!"),
      List("heart","blood","anatomy","pump"), 8, 12),

    Question("body-004", "human-body",
      "Why do we have fingerprints?",
      "Those little ridges on your fingertips do two jobs. First, they create friction so you can grip wet or slippery things without them sliding out of your hand. Second, they increase your sense of touch: the ridges press against microscopic vibration sensors in your fingertip, letting you feel textures far more precisely. The specific pattern of your ridges was set randomly by the way you pressed against the womb wall while growing — even identical twins have different prints.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/fingerprint.avif"), None,
      Some("/assets/audio/en/body-004.mp3"),
      List("Koala fingerprints look so similar to human ones that police forensic scientists have found them at crime scenes and been briefly confused!",
           "Your fingerprints start forming at week 10 of pregnancy — before you're even the size of a lime."),
      List("skin","grip","identity","fingerprints"), 8, 12),

    Question("body-005", "human-body",
      "Why do we sneeze?",
      "Your nose is the first defence against germs, dust, and pollen — it needs to clear out intruders fast. When something irritates the lining of your nasal passages, your brain sends an all-hands alarm. You automatically take a huge breath in, your eyes close, your chest and throat muscles tighten, and then — ACHOO! — a blast of air shoots out at over 160 km/h, launching the irritant far away from your body. You literally cannot keep your eyes open during a sneeze.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/sneeze.avif"), Some("/assets/animations/body/sneeze.json"),
      Some("/assets/audio/en/body-005.mp3"),
      List("A sneeze can spray up to 100,000 germ-containing droplets into the air at 160 km/h, travelling up to 8 metres — almost the full length of a school bus!",
           "Your brain hard-wires your eyes shut during a sneeze as a protection reflex. No one has ever been able to sneeze with their eyes open."),
      List("nose","immune","reflex","sneeze"), 8, 12),

    Question("body-006", "human-body",
      "Why do bones break and then heal?",
      "Bones are not dead material like rock — they're living tissue packed with cells. When a bone snaps, your body launches a four-stage repair mission. First, blood clots to seal the break. Then soft rubbery tissue called cartilage bridges the gap. Next, special builder cells called osteoblasts lay down new hard bone. Finally, other cells called osteoclasts sculpt it back into the right shape. The whole process can take 6–8 weeks — and the repaired spot is often stronger than before.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/bone-healing.avif"), Some("/assets/animations/body/bone-heal.json"),
      Some("/assets/audio/en/body-006.mp3"),
      List("Children's bones heal much faster than adults' because their builder cells (osteoblasts) are much more active.",
           "Your thigh bone (femur) is the strongest bone in your body. Engineers tested it and found it can support the weight of a small truck!"),
      List("bones","healing","skeleton","cells"), 8, 12),

    Question("body-007", "human-body",
      "Why do we dream?",
      "Dreams mostly happen during a stage of sleep called REM (Rapid Eye Movement), when your brain is surprisingly active. Scientists think dreaming helps your brain sort through everything that happened during the day — like a librarian filing away the important stuff and throwing out what you don't need. Some researchers also think dreams are your brain running practice simulations of scary situations, so you're more prepared for them in real life. Either way, you dream for about 2 hours every night, even if you don't remember it.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/dreaming.avif"), None,
      Some("/assets/audio/en/body-007.mp3"),
      List("People who were born blind from birth still dream — using sounds, smells, and feelings instead of pictures. Dreaming doesn't need eyes!",
           "Your brain is almost as active during dreaming sleep as when you're wide awake. That's why dreams feel completely real while they're happening."),
      List("brain","sleep","dreams","memory"), 8, 12),

    Question("body-008", "human-body",
      "Why does eating too much sugar give you a toothache?",
      "Your mouth is home to millions of bacteria that love sugar just as much as you do. When you eat something sweet, those bacteria immediately start feasting. As they digest the sugar, they release acid as a waste product — the same kind of acid that can dissolve metal if it's strong enough. Over time, that acid eats through the hard enamel coating on your teeth, making holes called cavities. Brushing your teeth removes the bacteria before they can eat enough sugar to make damaging amounts of acid.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/tooth-decay.avif"), Some("/assets/animations/body/tooth-bacteria.json"),
      Some("/assets/audio/en/body-008.mp3"),
      List("Tooth enamel is the hardest material in the entire human body — even harder than bone. But those bacteria acid attacks can still slowly beat it.",
           "You get exactly two sets of teeth in your lifetime: 20 baby teeth first, then 32 permanent ones. There are no more after that!"),
      List("teeth","sugar","bacteria","hygiene"), 8, 12),

    Question("body-009", "human-body",
      "Why does our skin wrinkle in water?",
      "This one surprised scientists. For a long time everyone assumed the skin was just soaking up water and swelling up. But it's actually your nervous system doing it on purpose! When you're in water, your nerves trigger the blood vessels under your fingertip skin to shrink, which makes the skin wrinkle up in ridges. Tests show that wrinkled wet fingers grip slippery or wet objects up to 12% better — like tyre tread gripping a wet road. Your body gave itself better grip automatically.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/wrinkled-fingers.avif"), None,
      Some("/assets/audio/en/body-009.mp3"),
      List("People who have nerve damage in their fingers don't get water wrinkles at all — which proved it's a nervous system response, not just soaking!",
           "The wrinkles start appearing after just 3.5 minutes in water. Your body is very quick to adapt."),
      List("skin","water","evolution","grip"), 8, 12),

    Question("body-010", "human-body",
      "Why do we have two eyes instead of one?",
      "Each eye sees the world from a slightly different angle — about 6 cm apart. Your brain takes those two slightly different pictures and compares them to work out how far away everything is. It's the same trick used to make 3D movies: two cameras, two slightly different views, and your brain blends them into one image with depth. One eye gives you a flat picture like a photo. Two eyes give you a full 3D world with distance judgment — crucial for catching a ball or judging a step.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/eyes.avif"), Some("/assets/animations/body/binocular.json"),
      Some("/assets/audio/en/body-010.mp3"),
      List("The image your eyes send to your brain is actually upside down and reversed! Your brain automatically flips and corrects it before you're aware of it.",
           "Eagles have vision 4–8 times sharper than humans and can spot a rabbit from over 3 kilometres away."),
      List("eyes","vision","brain","senses"), 8, 12)
  )
}
