package org.whysexplorer.content

import org.whysexplorer.models.{DifficultyLevel, Question}

object HumanBodyQuestions {

  val all: List[Question] = List(

    Question("body-001", "human-body",
      "Why do we yawn?",
      "Scientists used to think yawning cools the brain! When you're tired or bored, your brain temperature rises slightly. Opening your mouth wide brings in cool air that cools the blood going to the brain — like opening a window on a hot day. Yawning is also contagious because our brains are wired for empathy.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/yawn.avif"), Some("/assets/animations/body/yawn.json"),
      Some("/assets/audio/en/body-001.mp3"),
      List("Even reading the word 'yawn' or seeing a yawning emoji can trigger a yawn!",
           "Fetuses yawn in the womb from as early as 11 weeks."),
      List("brain","behavior","yawning"), 4, 12),

    Question("body-002", "human-body",
      "Why do we get goosebumps?",
      "Goosebumps are a leftover superpower from our hairy ancestors! When they were cold or scared, tiny muscles pulled their body hair upright, trapping warm air and making them look bigger to scare enemies. We still have the muscles, but not enough body hair — so we just get the bumps without the benefit.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/goosebumps.avif"), None,
      Some("/assets/audio/en/body-002.mp3"),
      List("The scientific word for goosebumps is 'cutis anserina' — Latin for 'goose skin'!",
           "Beautiful music can also cause goosebumps — scientists call these 'frisson' or 'aesthetic chills'."),
      List("skin","evolution","cold","fear"), 5, 12),

    Question("body-003", "human-body",
      "Why does our heart beat?",
      "Your heart is a powerful pump made of muscle. It squeezes about 100,000 times a day to push blood around your whole body. Blood carries oxygen and food to every cell and picks up waste. The beating you hear is the sound of valves inside your heart snapping shut to keep blood flowing the right direction.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/heart.avif"), Some("/assets/animations/body/heartbeat.json"),
      Some("/assets/audio/en/body-003.mp3"),
      List("Your heart will beat about 2.5 billion times in your lifetime — without ever taking a rest!",
           "A blue whale's heart is the size of a small car and beats only 4–8 times per minute."),
      List("heart","blood","anatomy","pump"), 4, 12),

    Question("body-004", "human-body",
      "Why do we have fingerprints?",
      "Fingerprints help you grip! The ridges on your fingertips create friction so you can pick up and hold slippery objects. They also increase sensitivity — the ridges help tiny vibration sensors detect texture. Even identical twins have different fingerprints because they're formed by random pressure in the womb.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/fingerprint.avif"), None,
      Some("/assets/audio/en/body-004.mp3"),
      List("Koalas have fingerprints almost identical to humans — even forensic experts can confuse them!",
           "Fingerprints start forming at week 10 of pregnancy."),
      List("skin","grip","identity","fingerprints"), 5, 12),

    Question("body-005", "human-body",
      "Why do we sneeze?",
      "Sneezing is your body's explosive way of clearing your nose! When dust, pollen, or germs irritate the lining of your nasal passage, your brain sends an emergency signal. You take a huge breath, muscles in your chest and throat tense up, then — ACHOO! — air blasts out at over 160 km/h, expelling the irritant.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/sneeze.avif"), Some("/assets/animations/body/sneeze.json"),
      Some("/assets/audio/en/body-005.mp3"),
      List("You cannot sneeze with your eyes open — your brain automatically closes them for protection!",
           "A sneeze expels air at up to 160 km/h and can spray droplets up to 8 metres away."),
      List("nose","immune","reflex","sneeze"), 4, 12),

    Question("body-006", "human-body",
      "Why do bones break and then heal?",
      "Bones are living tissue full of cells. When a bone breaks, your body launches a repair process: blood clots seal the break, then special cells called osteoblasts lay down new bone tissue like tiny builders. The break fills with a 'callus' of cartilage first, then hardens into solid bone — sometimes stronger than before!",
      DifficultyLevel.Medium,
      Some("/assets/images/body/bone-healing.avif"), Some("/assets/animations/body/bone-heal.json"),
      Some("/assets/audio/en/body-006.mp3"),
      List("Children's bones heal much faster than adults' because their osteoblasts are more active.",
           "The femur (thigh bone) is the strongest bone in your body — it can handle the weight of a truck!"),
      List("bones","healing","skeleton","cells"), 6, 12),

    Question("body-007", "human-body",
      "Why do we dream?",
      "Scientists still debate this! Leading theories: dreams help your brain sort and store memories from the day (like defragmenting a computer), they rehearse responses to dangerous situations to keep you safe, or they're your brain making random connections that feel like a story. REM sleep — when you dream most — is critical for learning.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/dreaming.avif"), None,
      Some("/assets/audio/en/body-007.mp3"),
      List("You dream for about 2 hours every night — even if you don't remember it!",
           "Blind people who were born without sight still dream, but using their other senses instead of images."),
      List("brain","sleep","dreams","memory"), 7, 12),

    Question("body-008", "human-body",
      "Why does eating too much sugar give you a toothache?",
      "Your mouth is home to bacteria that love sugar. When you eat sweets, the bacteria feast on the sugar and produce acid as waste. That acid slowly dissolves the hard enamel coating on your teeth, creating holes called cavities. Brushing removes the bacteria before they can make enough acid to damage enamel.",
      DifficultyLevel.Simple,
      Some("/assets/images/body/tooth-decay.avif"), Some("/assets/animations/body/tooth-bacteria.json"),
      Some("/assets/audio/en/body-008.mp3"),
      List("Tooth enamel is the hardest substance in your body — even harder than bone!",
           "You will grow exactly two sets of teeth in your life: 20 baby teeth, then 32 permanent ones."),
      List("teeth","sugar","bacteria","hygiene"), 5, 12),

    Question("body-009", "human-body",
      "Why does our skin wrinkle in water?",
      "The wrinkles are actually a superpower! When your hands are wet, your nervous system triggers blood vessels under the skin to constrict, causing the skin to wrinkle. Scientists found that wrinkled fingers grip wet objects up to 12% better — like the tread on a car tyre. It evolved to help our ancestors pick up wet food.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/wrinkled-fingers.avif"), None,
      Some("/assets/audio/en/body-009.mp3"),
      List("People with nerve damage in their fingers don't get water wrinkles — which proved the nervous system controls them.",
           "The wrinkles appear after just 3.5 minutes in water."),
      List("skin","water","evolution","grip"), 7, 12),

    Question("body-010", "human-body",
      "Why do we have two eyes instead of one?",
      "Two eyes give you 3D vision (depth perception)! Each eye sees the world from a slightly different angle. Your brain combines the two slightly different images to calculate exactly how far away objects are — like two cameras used for 3D movies. One eye alone gives a flat 2D view with no depth judgment.",
      DifficultyLevel.Medium,
      Some("/assets/images/body/eyes.avif"), Some("/assets/animations/body/binocular.json"),
      Some("/assets/audio/en/body-010.mp3"),
      List("Eagles have such powerful eyes they can spot a rabbit from 3.2 kilometres away!",
           "Your eyes are actually upside-down sensors — your brain flips the image right-side up instantly."),
      List("eyes","vision","brain","senses"), 6, 12)
  )
}
