package org.whysexplorer.content

import org.whysexplorer.models.{DifficultyLevel, Question}

object SpaceQuestions {

  val all: List[Question] = List(

    Question("space-006", "space",
      "Why does the Sun look yellow but is actually white?",
      "The Sun is actually white — it emits light of all colours equally. But when its light passes through Earth's atmosphere, blue and violet are scattered away, leaving the remaining mix looking yellow or orange to our eyes. From space, astronauts see the Sun as brilliant white.",
      DifficultyLevel.Medium,
      Some("/assets/images/space/sun-white.avif"), Some("/assets/animations/space/sun-glow.json"),
      Some("/assets/audio/en/space-006.mp3"),
      List("At midday the Sun looks more white; at sunrise/sunset it looks deep red because light travels through more atmosphere.",
           "The Sun fuses 620 million tonnes of hydrogen into helium every single second!"),
      List("sun","light","atmosphere","colour"), 5, 12),

    Question("space-007", "space",
      "Why is Mars called the Red Planet?",
      "Mars is covered in iron oxide — the same chemical as rust! Billions of years ago, Mars had water and oxygen, which reacted with iron in the soil to form rust. The wind then spread this red dust everywhere, colouring even the sky a butterscotch pink.",
      DifficultyLevel.Simple,
      Some("/assets/images/space/mars-red.avif"), None,
      Some("/assets/audio/en/space-007.mp3"),
      List("Mars has the largest volcano in the solar system — Olympus Mons is 3 times taller than Everest!",
           "A day on Mars is only 37 minutes longer than a day on Earth."),
      List("mars","planets","geology"), 4, 12),

    Question("space-008", "space",
      "Why do planets orbit the Sun in the same direction?",
      "All planets were born from the same spinning cloud of gas and dust called the solar nebula. As gravity pulled the cloud together, it spun faster — like a spinning skater pulling in their arms. Everything that formed from it inherited that same spin direction.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/solar-system.avif"), Some("/assets/animations/space/orbit-direction.json"),
      Some("/assets/audio/en/space-008.mp3"),
      List("Venus rotates backwards compared to its orbit — so the Sun rises in the west there!",
           "It took our solar system about 100 million years to fully form from that dust cloud."),
      List("planets","orbit","solar system","formation"), 8, 12),

    Question("space-009", "space",
      "Why does Saturn have rings?",
      "Saturn's rings are made of billions of chunks of ice and rock — from tiny grains to pieces as big as houses. Scientists think they came from moons, comets, or asteroids that got too close and were torn apart by Saturn's enormous gravity. They are only about 10–20 metres thick despite being 282,000 km wide!",
      DifficultyLevel.Medium,
      Some("/assets/images/space/saturn-rings.avif"), Some("/assets/animations/space/saturn-spin.json"),
      Some("/assets/audio/en/space-009.mp3"),
      List("Saturn's rings are disappearing — they are being pulled into the planet as rain at 10,000 kg per second!",
           "All four gas giants (Jupiter, Saturn, Uranus, Neptune) have rings, but Saturn's are by far the brightest."),
      List("saturn","rings","planets","gravity"), 6, 12),

    Question("space-010", "space",
      "Why is Pluto no longer called a planet?",
      "In 2006, scientists decided a planet must do three things: orbit the Sun, be round due to its own gravity, and 'clear the neighbourhood' of other objects in its orbit. Pluto passes the first two tests but shares its orbit with thousands of other Kuiper Belt objects — so it's now called a 'dwarf planet'.",
      DifficultyLevel.Medium,
      Some("/assets/images/space/pluto.avif"), None,
      Some("/assets/audio/en/space-010.mp3"),
      List("Pluto is smaller than Earth's Moon!",
           "Pluto has a heart-shaped plain of frozen nitrogen visible from space called Tombaugh Regio."),
      List("pluto","planets","solar system","classification"), 6, 12),

    Question("space-011", "space",
      "Why does the Moon cause ocean tides?",
      "The Moon's gravity pulls on Earth's water. The side of Earth facing the Moon gets pulled toward it, creating a bulge of water (high tide). On the opposite side, Earth itself gets pulled away from the water, creating another bulge. As Earth rotates through these bulges, most coastlines get two high tides per day.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/tides.avif"), Some("/assets/animations/space/tides.json"),
      Some("/assets/audio/en/space-011.mp3"),
      List("The Sun also creates tides — when Sun, Moon, and Earth align, we get extra-strong 'spring tides'!",
           "The Moon is slowly stealing Earth's rotational energy — our days get 1.4 milliseconds longer each century."),
      List("moon","tides","gravity","ocean"), 8, 12),

    Question("space-012", "space",
      "Why can't we see stars during the day?",
      "Stars are always there — we just can't see them because the Sun's light scatters across our atmosphere and overwhelms their faint light. It's like trying to see a candle next to a spotlight. During a total solar eclipse, when the Moon blocks the Sun, stars actually become briefly visible in daytime!",
      DifficultyLevel.Simple,
      Some("/assets/images/space/stars-day.avif"), None,
      Some("/assets/audio/en/space-012.mp3"),
      List("From the bottom of a deep well or mine shaft, you can sometimes glimpse stars even in daytime!",
           "The nearest star to Earth after the Sun is Proxima Centauri — 4.24 light-years away."),
      List("stars","light","atmosphere","day"), 5, 12),

    Question("space-013", "space",
      "Why is space completely dark if there are billions of stars?",
      "This is called Olbers' Paradox! The answer: the universe isn't infinitely old. Light from the most distant stars hasn't had enough time to reach us yet (the universe is ~13.8 billion years old). Also, the universe is expanding, which stretches starlight into longer, invisible wavelengths. So we see darkness between stars.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/dark-space.avif"), None,
      Some("/assets/audio/en/space-013.mp3"),
      List("If the universe were infinitely old and static, the night sky would be as bright as the surface of the Sun!",
           "The darkness of space is actually filled with the Cosmic Microwave Background — leftover glow from the Big Bang."),
      List("space","light","universe","paradox"), 9, 12),

    Question("space-014", "space",
      "Why do comets have tails?",
      "Comets are dirty snowballs of ice and rock from the outer solar system. When one gets close to the Sun, the heat vaporises its ice, releasing gas and dust. Solar wind blows this material away from the Sun, forming two tails — one made of dust and one of glowing gas — that always point away from the Sun.",
      DifficultyLevel.Medium,
      Some("/assets/images/space/comet.avif"), Some("/assets/animations/space/comet-tail.json"),
      Some("/assets/audio/en/space-014.mp3"),
      List("Comet tails can be tens of millions of kilometres long!",
           "The Halley's Comet visits our solar system every 75–76 years. The next visit will be in 2061."),
      List("comets","solar system","ice","sun"), 6, 12),

    Question("space-015", "space",
      "Why does gravity pull things down?",
      "Gravity is a force that every object with mass exerts on every other object. Earth is enormously massive, so its gravitational pull is very strong. Albert Einstein explained it even better: mass bends the fabric of spacetime like a bowling ball on a trampoline, and other objects roll toward that dip — which we feel as 'falling down'.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/gravity.avif"), Some("/assets/animations/space/gravity-curve.json"),
      Some("/assets/audio/en/space-015.mp3"),
      List("Gravity is the weakest of the four fundamental forces of nature — yet it holds galaxies together!",
           "On the Moon, you would weigh only one-sixth of what you weigh on Earth."),
      List("gravity","physics","earth","spacetime"), 8, 12)
  )
}
