package org.whysexplorer.content

import org.whysexplorer.models.{DifficultyLevel, Question}

object SpaceQuestions {

  val all: List[Question] = List(

    Question("space-006", "space",
      "Why does the Sun look yellow but is actually white?",
      "Here's a trick the atmosphere plays on your eyes. The Sun sends out light of every colour, which mixed together looks white. But as that light passes through all the air above us, blue bounces away in every direction (which is why the sky looks blue!). Once you remove the blue, what's left looks yellow or orange to your eyes. Astronauts above the atmosphere see the Sun as a blazing white disc — exactly the colour it really is.",
      DifficultyLevel.Medium,
      Some("/assets/images/space/sun-white.avif"), Some("/assets/animations/space/sun-glow.json"),
      Some("/assets/audio/en/space-006.mp3"),
      List("At midday the Sun looks more white because the light travels through the least amount of air. At sunrise and sunset it travels through way more air, making it turn deep red.",
           "The Sun burns through 620 million tonnes of hydrogen every single second — and it's been doing that for 4.6 billion years!"),
      List("sun","light","atmosphere","colour"), 8, 12),

    Question("space-007", "space",
      "Why is Mars called the Red Planet?",
      "Mars is basically a rusty planet. Billions of years ago, Mars had water and oxygen, and those reacted with the iron in the soil — exactly the same chemical reaction that makes a bike go rusty. The rusty dust got blown around by Martian winds until it coated everything: the rocks, the plains, the sky. If you stood on Mars, the air would look a butterscotch colour because of all the rust dust floating in it.",
      DifficultyLevel.Simple,
      Some("/assets/images/space/mars-red.avif"), None,
      Some("/assets/audio/en/space-007.mp3"),
      List("Mars has the biggest volcano in the whole solar system. Olympus Mons is 25 km tall — nearly 3 times taller than Mount Everest!",
           "One day on Mars is only 37 minutes longer than a day on Earth — so your daily schedule wouldn't change much if you lived there."),
      List("mars","planets","geology"), 8, 12),

    Question("space-008", "space",
      "Why do planets orbit the Sun in the same direction?",
      "All the planets were born from the same giant spinning cloud of gas and dust about 4.6 billion years ago. As gravity pulled the cloud together, it spun faster and faster — just like a spinning skater pulls their arms in and speeds up. Everything that formed from that spinning cloud — planets, moons, asteroids — inherited the same spin direction. It's like everyone at a roundabout going the same way because they all jumped on from the same side.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/solar-system.avif"), Some("/assets/animations/space/orbit-direction.json"),
      Some("/assets/audio/en/space-008.mp3"),
      List("Venus spins backwards compared to its orbit around the Sun. If you were on Venus, the Sun would rise in the west and set in the east!",
           "Our whole solar system took about 100 million years to form from that original spinning dust cloud."),
      List("planets","orbit","solar system","formation"), 8, 12),

    Question("space-009", "space",
      "Why does Saturn have rings?",
      "Saturn's rings are made of billions of chunks of ice and rock — some tiny as a grain of sand, others as big as a house. Scientists think the rings came from moons, comets, or asteroids that got too close to Saturn and were ripped apart by its enormous gravity. The crazy thing is that this ring system is enormous in width (282,000 km across) but only about 10–20 metres thick — thinner compared to its size than a sheet of paper!",
      DifficultyLevel.Medium,
      Some("/assets/images/space/saturn-rings.avif"), Some("/assets/animations/space/saturn-spin.json"),
      Some("/assets/audio/en/space-009.mp3"),
      List("Saturn's rings are slowly disappearing — gravity pulls ring material into the planet as rain at 10,000 kg per second. In about 100 million years, the rings will be gone!",
           "All four gas giants (Jupiter, Saturn, Uranus, Neptune) have ring systems, but Saturn's are by far the thickest and brightest."),
      List("saturn","rings","planets","gravity"), 8, 12),

    Question("space-010", "space",
      "Why is Pluto no longer called a planet?",
      "In 2006, scientists agreed that to count as a full planet, a world must do three things: orbit the Sun, be round from its own gravity, and clear other objects out of its orbital path. Pluto does the first two fine. But it shares its path around the Sun with thousands of other icy objects in a region called the Kuiper Belt. It never 'cleared the neighbourhood,' so scientists gave it the new title of dwarf planet — like being a planet but in a different league.",
      DifficultyLevel.Medium,
      Some("/assets/images/space/pluto.avif"), None,
      Some("/assets/audio/en/space-010.mp3"),
      List("Pluto is actually smaller than Earth's Moon — it's about two-thirds the size!",
           "Pluto has a giant heart-shaped patch of frozen nitrogen on its surface, nicknamed Tombaugh Regio. It's visible from space."),
      List("pluto","planets","solar system","classification"), 8, 12),

    Question("space-011", "space",
      "Why does the Moon cause ocean tides?",
      "The Moon's gravity reaches all the way to Earth and gives our oceans a gentle tug. The ocean on the side of Earth nearest the Moon gets pulled toward it, making the water bulge up — that's a high tide. At the same time, Earth itself gets pulled slightly toward the Moon, so the ocean on the far side gets left behind in another bulge. As Earth spins around, different coastlines pass through those two bulges — which is why most places get two high tides every day.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/tides.avif"), Some("/assets/animations/space/tides.json"),
      Some("/assets/audio/en/space-011.mp3"),
      List("The Sun also creates tides. When the Sun, Moon, and Earth line up (at new moon and full moon), we get extra-high 'spring tides'!",
           "The Moon is slowly stealing Earth's spinning energy. Our days are getting 1.4 milliseconds longer every century because of it."),
      List("moon","tides","gravity","ocean"), 8, 12),

    Question("space-012", "space",
      "Why can't we see stars during the day?",
      "Stars are always there — they don't disappear at sunrise! The problem is that our Sun is also a star, and it's incredibly bright. Its light scatters all across our atmosphere and fills the sky with so much brightness that the faint light from distant stars just gets completely swamped. It's like trying to see a candle flame next to a stadium floodlight — you can't. During a total solar eclipse, when the Moon blocks the Sun, stars briefly pop back into view in the middle of the day.",
      DifficultyLevel.Simple,
      Some("/assets/images/space/stars-day.avif"), None,
      Some("/assets/audio/en/space-012.mp3"),
      List("If you climb down to the bottom of a very deep well or mine shaft, you can sometimes spot bright stars even in daytime — because the sky you see is a narrow strip with less scattered light!",
           "The nearest star to Earth after the Sun is Proxima Centauri — 4.24 light-years away. Light from it takes over 4 years to reach your eyes."),
      List("stars","light","atmosphere","day"), 8, 12),

    Question("space-013", "space",
      "Why is space completely dark if there are billions of stars?",
      "This puzzle is called Olbers' Paradox and it stumped scientists for centuries. Here's the answer: the universe hasn't existed forever. It started about 13.8 billion years ago, so light from the most distant stars simply hasn't had enough time to reach us yet. Also, the universe is expanding in every direction, which stretches starlight into invisible wavelengths we can't see. Those two facts together mean that even though stars are everywhere, most of their light never makes it to your eyes.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/dark-space.avif"), None,
      Some("/assets/audio/en/space-013.mp3"),
      List("If the universe were infinite and had existed forever, the night sky would be as bright as the surface of the Sun — everywhere, in every direction, 24 hours a day!",
           "Space isn't totally dark. It's filled with the Cosmic Microwave Background — an invisible glow left over from the Big Bang that fills the entire universe."),
      List("space","light","universe","paradox"), 8, 12),

    Question("space-014", "space",
      "Why do comets have tails?",
      "Comets are like giant dirty snowballs — lumps of ice, rock, and dust from the outer edges of our solar system. Most of the time they're frozen solid and invisible. But when a comet swings close to the Sun, the heat boils off the ice and releases gas and dust. The Sun constantly shoots out a stream of particles called solar wind, which blows that gas and dust away from the comet into a glowing tail — always pointing directly away from the Sun, no matter which direction the comet is moving.",
      DifficultyLevel.Medium,
      Some("/assets/images/space/comet.avif"), Some("/assets/animations/space/comet-tail.json"),
      Some("/assets/audio/en/space-014.mp3"),
      List("Comet tails can stretch for tens of millions of kilometres — longer than the distance from Earth to the Sun!",
           "Halley's Comet visits the inner solar system every 75–76 years. It was last seen in 1986 and will return in 2061."),
      List("comets","solar system","ice","sun"), 8, 12),

    Question("space-015", "space",
      "Why does gravity pull things down?",
      "Everything with mass (stuff made of matter) pulls on everything else — that's just a fundamental rule of the universe called gravity. Earth is enormous, so its pull is very strong. Albert Einstein gave us an even better picture: imagine a heavy ball sitting on a stretched rubber sheet. It sinks and makes a curved dip. Earth's mass does that to the invisible fabric of space, and other objects roll toward that dip — which is what we feel as 'falling down'.",
      DifficultyLevel.Advanced,
      Some("/assets/images/space/gravity.avif"), Some("/assets/animations/space/gravity-curve.json"),
      Some("/assets/audio/en/space-015.mp3"),
      List("Gravity is actually the weakest of the four fundamental forces — a small magnet can fight Earth's entire gravitational pull and lift a paperclip off a table!",
           "On the Moon, gravity is only one-sixth as strong as Earth's. You could jump 6 times higher there with exactly the same effort."),
      List("gravity","physics","earth","spacetime"), 8, 12)
  )
}
